# version: '1.1'

services:
  sneakers-api:
    container_name: sneakers-api
    restart: always
    image: node:20.10.0
    ports:
      - 4001:3007
    volumes:
      - ./:/usr/src/sneakers
    working_dir: /usr/src/sneakers

    networks:
      - monorepo_network

    # FOR PRODUCTION
    command: bash -c "rm -rf dist && npm install && npm run build && npm run start:prod"

  sneakers-batch:
    container_name: sneakers-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - 4002:3008
    volumes:
      - ./:/usr/src/sneakers
    working_dir: /usr/src/sneakers

    networks:
      - monorepo_network

    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo_network:
    driver: bridge
# sneakers-next:  localhost:4000 => container:3000
# sneakers-api:   localhost:4001 => container:3007
# sneakers-batch: localhost:4002 => container:3008

# docker compose up -d
# docker compose up stop
# docker compose up start
# docker compose up restart
# docker compose up stop && docker compose rm -f
